### ISSUE TITLE
To-Do list for Milestone 3

### ISSUE THREAD

**Issue by liuyuwei169** [UBC-MDS/us-police-shootings-analysis#15]
- [x] Correct the title to clearly state the purpose of the app for the users.

- [x] Numbers displayed on hovering not required to have high precision.

- [x] It is great that the total frequency plotted on the map is updated each time new filters are selected, but it would be more helpful to be clear about this to avoid confusion that it is percentage out of total shootings. Perhaps add a description or change the legend on the color intensity plot to say "frequency out of variables currently selected'

- [x] The bar chart is not very readable, for the frequency you could add a label that describes that it is the frequency of "number of people who were shot" or "shooting incidents"

- [x] Add a bar chart that ranks the top (or top ten) most dangerous states to see a clearer comparison.

- [x] Add an “all” option in every drop-down menu.

**Comment by adityashrm21** [comment]
addressed all!
