### ISSUE TITLE
TO-Do List for milestone 4

### ISSUE THREAD

**Issue by liuyuwei169** [UBC-MDS/us-police-shootings-analysis#22]
- [x] Create a bar chart of race in general.
- [x] Add the number of death by race on hovering over the states
- [x] Add the click feature on each state so it will show the plot of number of death over time in each state
